Add https on hot
JeffreyWay/laravel-mix pull request #2783
Opened 2021-01-20 16:41 UTC by soilSpoon

```
error: unknown option '--https'
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! working-note@ hot: `mix watch --hot --https`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the working-note@ hot script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

I currently have the same problem as above on laravel-mix 6.
Fixes an issue where https is not properly supported when laravel-mix is upgraded to version 6.

2021-01-25 22:37 UTC, thecrypticace commented on src/config.js
> +            isHttps: !!argv.https,
```suggestion
            https: !!argv.https,
```

2021-01-25 22:37 UTC, thecrypticace commented on src/builder/WebpackConfig.js
> +        const {isHttps, host, port} = Config.hmrOptions;
```suggestion
        const {https, host, port} = Config.hmrOptions;
```

2021-01-25 22:37 UTC, thecrypticace commented on src/builder/WebpackConfig.js
> +        const protocol = isHttps ? 'https' : 'http';
```suggestion
        const protocol = https ? 'https' : 'http';
```

2021-01-25 22:37 UTC, thecrypticace commented on src/builder/WebpackConfig.js
> +            https: isHttps,
```suggestion
            https: https,
```

2021-01-25 22:39 UTC, thecrypticace commented
Left a few suggestions. Can you also update the types under `types/config.d.ts`?

2021-01-27 21:01 UTC, thecrypticace commented
Thanks @soilSpoon, I'll be reviewing this over the weekend.

2021-02-01 22:38 UTC, muhammedraqeeb requested changes

2021-02-01 22:38 UTC, muhammedraqeeb commented on bin/cli.js
>          .action(cmd =>
.option( ' --https', 'Enable https.', false)

2021-02-02 15:05 UTC, merged

2021-02-04 13:44 UTC, rleger commented
Can you give a way to make hmr work with https websites ? trying to reproduce code from the mix 5.0 documentation but without success. Thanks !!

https://laravel-mix.com/docs/5.0/hot-module-replacement

2021-02-04 14:34 UTC, soilSpoon commented
You can use `npx mix watch --hot`.
but currently, this PR has not been released.
Please try after this PR is released.